#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

dotfiles="$HOME/.dotfiles"
source "$dotfiles/zsh/alias"
source "$dotfiles/zsh/custom-functions"

if [[ "$TERM_PROGRAM" != 'iTerm.app' ]]; then
  export COMPATIBILITY=1
fi

[ -z "$COMPATIBILITY" ] && source "$dotfiles/zsh/promptline.sh"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
