#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

if [[ "$TERM_PROGRAM" != 'iTerm.app' ]]; then
  export COMPATIBILITY=1
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export FZF_DEFAULT_COMMAND="(ag -g '') 2> /dev/null"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

_fzf_compgen_path() {
  (ag -g '') 2> /dev/null
}

# NOTES:
# Slow zsh? Run `compaudit` and check if permissions are 755
#
# Profiling
# Enable this line at the beginning of the zshrc
# `$ zmodload zsh/zprof`
# run zprof after terminal loaded

eval "$(direnv hook zsh)"
export MANPAGER="nvim -c 'set ft=man' - "
