#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

source "${ZDOTDIR:-$HOME}/.zprezto/extras/alias"
source "${ZDOTDIR:-$HOME}/.zprezto/extras/custom-functions"

if [[ "$TERM_PROGRAM" != 'iTerm.app' ]]; then
  export COMPATIBILITY=1
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
