#!/bin/sh

# general
alias al='rg --files-with-matches --smart-case'
alias vi='nvim'

# work
alias mclient='bundle exec mina full_deploy HOST=client1 BRANCH=`gcb`'
alias mqa='bundle exec mina full_deploy HOST=qa.ossd.co BRANCH=`gcb`'

alias rubo='git diff --name-only -z -- \*.{rb,rake} | xargs -0 bundle exec rubocop -a -R -D'
alias rubox='bundle exec rubocop -a -R -D **/*.{rb,rake}'

alias eslint='git_root; yarn run eslint'
alias eslint_all="git_root; find app/assets/javascripts/visual_directory -name '*.jsx' -or -name '*.es6' | xargs -P4 -n100 bin/eslint | tee eslint_output "
alias eslintx="yarn run eslintx"
# alias eslintx_all="eslint_all --fix"

alias vd='cd ~/OSS/huddle/app/assets/javascripts/visual_directory'
alias vdc='vd && cd components '

alias spec='gss -- spec/**/*.rb | awk "{ print \$NF }" | xargs bundle exec rspec'

alias graylog='ssh -N -L 12900:localhost:12900 -L 9000:localhost:9000 root@kraken.officespacesoftware.com'
alias forward_local='ssh -N -tt osadmin@builder.ossd.co -R 10000:localhost:3000'

alias reyarn='git_root; rm -rf node_modules; yarn install;'

# git
alias gb='git branch'
alias gcm='git checkout master'
alias gcmt='git commit'
alias gco='git checkout'
alias gdca='git diff --cached'
alias gss='git status -s'
alias gcb='git rev-parse --abbrev-ref HEAD'
alias git_root='cd $(git rev-parse --show-toplevel) ; '
alias conflict='gss | grep UU | cut -d " " -f 2 '
alias vdirty='$EDITOR $( git status -s | awk "{ print \$NF }" ) '
alias gdev='git_root; git apply ../dev.patch'

# vagrant
# alias vd='vagrant destroy'
alias vh='vagrant halt'
alias vp='vagrant provision'
alias vss='vagrant status'
alias vssh='vagrant ssh'
alias vu='vagrant up'

# misc
alias now='date +"%R"'
alias today='$EDITOR $HOME/OSS/notes/daily/$( gdate +%F ).md'

alias weather='curl wttr.in'

alias nyan='telnet nyancat.dakko.us'
alias tmate='COMPATIBILITY=1 tmate'

# dotfiles
alias lsd='ls -d .*'
alias prezto='cd ~/.zprezto && vdirty'
alias htree='tree -a -I plugged\|\.git'
alias zshrc='$EDITOR $HOME/.zshrc'
