#!/bin/sh

# needs some work
# alias rubo="git diff --diff-filter=ACMR --name-only -z origin/master -- \*.{rb,rake} | xargs -0 bundle exec rubocop -R -D"
alias rubo="git diff --name-only -z -- \*.{rb,rake} | xargs -0 bundle exec rubocop -a -R -D"
alias rubox='bundle exec rubocop -a -R -D **/*.{rb,rake}'
alias al="ag --files-with-matches --smart-case"
alias vt="xargs -o nvim -p"
alias vi="nvim"
alias nyan="telnet nyancat.dakko.us"
alias nw='tmux new-window'
alias rs='rails s -b 127.0.0.1'
alias tmate='COMPATIBILITY=1 tmate'
alias vu='vagrant up'
alias vp='vagrant provision'
alias vss='vagrant status'
alias vd='vagrant destroy'
alias vh='vagrant halt'
alias vssh='vagrant ssh'
alias guo='git_up_oss'
alias zshrc='nvim ~/.zshrc'
alias vd='cd ~/OSS/huddle/app/assets/javascripts/visual_directory'
alias v='f -e nvim'
alias mclient='bundle exec mina full_deploy HOST=client1 BRANCH=`git rev-parse --abbrev-ref HEAD`'
alias mqa='bundle exec mina full_deploy HOST=qa.ossd.co BRANCH=`git rev-parse --abbrev-ref HEAD`'
alias weather='curl wttr.in'
alias today='date +"%F (%a %b %d)"'
alias now='date +"%R"'
alias spec="git diff --name-only -z -- spec/**/*.rb | xargs -0 bundle exec rspec"
# alias spec="git diff --porcelain -z --spec/**/*.rb | xargs -0 bundle exec rspec"
alias vdirty="git status -s | awk '{print \$2}' | xargs -o nvim"

alias gss="git status -s"
alias gb="git branch"
alias gco="git checkout"
alias gcm="git checkout master"
alias gdca="git diff --cached"


alias lsd='ls -d .*'
